### ISSUE TITLE
Won't build on linux

### ISSUE THREAD

**Issue by shosca** [buunguyen/octotree#452]
### Description
`npm run dist` fails

### Environment (if bug)

* Octotree version: git master
* Browser & version: n/a
* OS & version: Archlinux
* Screenshot, if any (drag an image here)

```
[09:12:44] Error: Command `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --pack-extension=/home/serkan/src/octotree/tmp/chrome --pack-extension-key=/home/serkan/.ssh/chrome.pem` exited with code 127
    at ChildProcess.handleSubShellExit (/home/serkan/src/octotree/node_modules/gulp-run/command.js:166:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[09:12:44] 'dist' errored after 329 ms
[09:12:44] Error: [object Object]
    at formatError (/home/serkan/src/octotree/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/serkan/src/octotree/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:115:13)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/home/serkan/src/octotree/node_modules/orchestrator/index.js:264:8)
    at /home/serkan/src/octotree/node_modules/orchestrator/index.js:275:23
    at finish (/home/serkan/src/octotree/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/serkan/src/octotree/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/home/serkan/src/octotree/node_modules/gulp-run-sequence/index.js:35:5)
    at Gulp.onError (/home/serkan/src/octotree/node_modules/gulp-run-sequence/index.js:41:4)
$ "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --pack-extension=/home/serkan/src/octotree/tmp/chrome --pack-extension-key=/home/serkan/.ssh/chrome.pem
```

**Comment by buunguyen** [comment]
It won't. Current build script targets OSX. I will accept PR.
